export const CAROUSEL_START = 'CAROUSEL_START';
export const CAROUSEL_SUCCESS = 'CAROUSEL_SUCCESS';
export const CAROUSEL_FAIL = 'CAROUSEL_FAIL';

export const CATEGORIES_START = 'CATEGORIES_START';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAIL = 'CATEGORIES_FAIL';

export const NEWARRIVALS_START = 'NEWARRIVALS_START';
export const NEWARRIVALS_SUCCESS = 'NEWARRIVALS_SUCCESS';
export const NEWARRIVALS_FAIL = 'NEWARRIVALS_FAIL';

export const BESTPRICES_START = 'BESTPRICES_START';
export const BESTPRICES_SUCCESS = 'BESTPRICES_SUCCESS';
export const BESTPRICES_FAIL = 'BESTPRICES_FAIL';

export const FEATURES_START = 'FEATURES_START';
export const FEATURES_SUCCESS = 'FEATURES_SUCCESS';
export const FEATURES_FAIL = 'FEATURES_FAIL';

export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_SUB_CATEGORY = 'SET_SUB_CATEGORY';
export const SET_ADDITIONAL_CATEGORY = 'SET_ADDITIONAL_CATEGORY';
export const SET_PRODUCT = 'SET_PRODUCT'







