export const LOGO_START = 'LOGO_START';
export const LOGO_SUCCESS = 'LOGO_SUCCESS';
export const LOGO_FAIL = 'LOGO_FAIL';

export const ALLPRODUCTS_START = 'ALLPRODUCTS_START';
export const ALLPRODUCTS_SUCCESS = 'ALLPRODUCTS_SUCCESS';
export const ALLPRODUCTS_FAIL = 'ALLPRODUCTS_FAIL';

export const SEARCH_CATEGORY_OPTION_START = 'SEARCH_CATEGORY_OPTION_START';
export const SEARCH_CATEGORY_OPTION_SUCCESS = 'SEARCH_CATEGORY_OPTION_SUCCESS';
export const SEARCH_CATEGORY_OPTION_FAIL = 'SEARCH_CATEGORY_OPTION_FAIL';







